### ISSUE TITLE
some buttons functions

### ISSUE THREAD

**Issue by pokane84** [mjs2020/trademap#36]
do the download buttons etc work? 

the 'feedback' button - will this be a feature and if so do I need to provide anything for it?

**Comment by mjs2020** [comment]
Will check download buttons. For the feedback, if you would like to have it
you should set up a survey monkey or Google form (or similar solution).

**Comment by pokane84** [comment]
No problem about download buttons. 

Regarding Feedback, would like this removed as the contact email is available.
